// <auto-generated />
namespace GuildWars2.GuildInfo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addmembers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmembers));
        
        string IMigrationMetadata.Id
        {
            get { return "201704062336332_add-members"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
