// <auto-generated />
using GuildWars2.Data.Database;
using GuildWars2.Data.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace GuildWars2.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180511010208_model-v1.1")]
    partial class modelv11
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("GuildWars2.Data")
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GuildWars2.Data.Model.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("GuildWars2.Data.Model.CategoryValue", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoryID");

                    b.Property<DateTime>("Date");

                    b.Property<int>("Delta");

                    b.Property<int>("UserID");

                    b.Property<int>("Value");

                    b.HasKey("ID");

                    b.ToTable("CategoryValue");
                });

            modelBuilder.Entity("GuildWars2.Data.Model.Dye", b =>
                {
                    b.Property<int>("UserID");

                    b.Property<int>("ItemID");

                    b.Property<DateTime>("Date");

                    b.HasKey("UserID", "ItemID");

                    b.ToTable("Dye");
                });

            modelBuilder.Entity("GuildWars2.Data.Model.Item", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<DateTime>("Date");

                    b.Property<int>("Delta");

                    b.Property<int>("ItemID");

                    b.Property<int>("Location");

                    b.Property<int>("SkinID");

                    b.Property<int>("StatID");

                    b.Property<int>("UserID");

                    b.HasKey("ID");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("GuildWars2.Data.Model.Skin", b =>
                {
                    b.Property<int>("UserID");

                    b.Property<int>("SkinID");

                    b.Property<DateTime>("Date");

                    b.HasKey("UserID", "SkinID");

                    b.ToTable("Skin");
                });

            modelBuilder.Entity("GuildWars2.Data.Model.User", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key");

                    b.HasKey("ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("GuildWars2.Data.Model.WalletEntry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<int>("CurrencyID");

                    b.Property<DateTime>("Date");

                    b.Property<int>("Delta");

                    b.Property<int>("UserID");

                    b.HasKey("ID");

                    b.ToTable("Wallet");
                });
#pragma warning restore 612, 618
        }
    }
}
