//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace GuildWars2DB.Model
{
	/// <summary>
	/// Database       : Gw2Database
	/// Data Source    : Gw2Database
	/// Server Version : 3.8.8.3
	/// </summary>
	public partial class Gw2DatabaseDB : LinqToDB.Data.DataConnection
	{
		public ITable<GuildLogTableEntry> GuildLogs { get { return this.GetTable<GuildLogTableEntry>(); } }

		public Gw2DatabaseDB()
		{
			InitDataContext();
		}

		public Gw2DatabaseDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("GuildLog")]
	public partial class GuildLogTableEntry
	{
		[PrimaryKey, Identity] public int      ID        { get; set; } // integer
		[Column,     Nullable] public int?     LogID     { get; set; } // integer
		[Column,     Nullable] public DateTime? Time      { get; set; } // datetime
		[Column,     Nullable] public string    User      { get; set; } // text(max)
		[Column,     Nullable] public string    Type      { get; set; } // text(max)
		[Column,     Nullable] public string    Operation { get; set; } // text(max)
		[Column,     Nullable] public int?     Count     { get; set; } // integer
		[Column,     Nullable] public int?     Coins     { get; set; } // integer
		[Column,     Nullable] public int?     ItemID    { get; set; } // integer
		[Column,     Nullable] public string    MOTD      { get; set; } // text(max)
		[Column,     Nullable] public string    InvitedBy { get; set; } // text(max)
		[Column,     Nullable] public string    KickedBy  { get; set; } // text(max)
		[Column,     Nullable] public string    ChangedBy { get; set; } // text(max)
		[Column,     Nullable] public string    OldRank   { get; set; } // text(max)
		[Column,     Nullable] public string    NewRank   { get; set; } // text(max)
		[Column,     Nullable] public string    UpgradeID { get; set; } // text(max)
		[Column,     Nullable] public string    Action    { get; set; } // text(max)
	}

	public static partial class TableExtensions
	{
		public static GuildLogTableEntry Find(this ITable<GuildLogTableEntry> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}
	}
}
